name: Android

# Triggered when code is pushed to any branch in a repository
on: push

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Gradle Cache https://github.com/actions/cache/blob/main/examples.md#java---gradle
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Yarn Cache: https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install node dependencies
        run: yarn install --frozen-lockfile
        
      - name: Check Permission
        run: cd android && chmod +x ./gradlew

      - name: Bundle *.apk
        run: cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: MY APK FILE
          path: android/app/build/outputs/apk/release/app-release.apk
          
      - name: Bundle *.aap
        run: cd android && ./gradlew bundleRelease 

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: MY AAB FILE
          path: android/app/build/outputs/bundle/release/app-release.aab
