name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
        # Build Command

      - name: Build Android ${{inputs.environment == 'release' && 'Release' || 'Debug'}}
        run: |
          cd android && ./gradlew assembleRelease
      # Upload to Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MuxStream.apk
          path: "android/app/build/outputs/apk/release/MuxStream.apk"
