name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Build Android
        run: cd android && ./gradlew assembleRelease
      # Upload to Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MuxStream.apk
          path: "android/app/build/outputs/apk/release/MuxStream.apk"
